spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Mysql
  sql:
    init:
      continue-on-error: true
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
