server:
  port: 8080

spring:
  application:
    name: impp

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/impp_db?allowPublicKeyRetrival=true&sslMode=DISABLED
    username: root
    password: bicicleta123



